#!/usr/bin/env node
/**
 * Caption preview-vs-export comparator.
 *
 * Renders the SAME words at the SAME timestamps two ways and puts them side by
 * side, so a preset can be checked without exporting a video:
 *
 *   left  = export      .ass generated by BuildsAnimatedCaptions, drawn by libass (ffmpeg)
 *   right = editor      the real CaptionPreview.vue CSS, drawn by headless Chrome
 *
 * The preview column pulls the component's own <style> block and the shared
 * captionPresets engine straight off disk, so it can't drift from what the app
 * actually renders. CSS animations are frozen and seeked with a negative
 * animation-delay, which makes each frame deterministic.
 *
 * Usage:
 *   node tools/caption-compare.mjs                    # every preset
 *   node tools/caption-compare.mjs beast karaoke      # just these
 *   node tools/caption-compare.mjs --backdrop box     # with the panel on
 *   node tools/caption-compare.mjs --open beast       # open the sheet when done
 *
 * Output: tools/caption-compare-out/<preset>.png
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "tools", "caption-compare-out");
const TMP = fs.mkdtempSync(path.join(os.tmpdir(), "capcmp-"));

const CHROME = [
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/usr/bin/chromium",
  "/usr/bin/google-chrome",
].find((p) => fs.existsSync(p));

// A frame every ~0.45s catches entry animations rather than only settled text.
const TIMES = [0.30, 0.62, 0.95, 1.45, 1.95, 2.45];
const WORDS = [
  ["Ever", 0.0, 0.56], ["notice", 0.56, 0.94], ["how", 0.94, 1.14],
  ["your", 1.14, 1.4], ["coffee", 1.4, 1.78], ["tastes", 1.78, 2.18],
  ["better", 2.18, 2.49], ["in", 2.49, 2.68], ["a", 2.68, 2.84],
  ["certain", 2.84, 3.3], ["mug", 3.3, 3.72],
].map(([text, start, end]) => ({ text, start, end }));

const W = 1080, H = 1920;
const BASE_FONT = 17;            // editor CAPTION_SIZE_MAP medium, at a 480-tall pane
const EXPORT_FONT = Math.round((BASE_FONT * H) / 480);
const SETTINGS = {
  color: "#ffffff",
  highlight_color: "#ffd21e",
  highlight_mode: process.env.CAPTION_COMPARE_MODE || "line_by_line",
  highlight_style: "color",
  panel_color: null,
};

const argv = process.argv.slice(2);
const backdrop = argv.includes("--backdrop");
const openWhenDone = argv.includes("--open");
const wanted = argv.filter((a) => !a.startsWith("--"));

const { CAPTION_ANIMATIONS, animationByKey, effectiveChunk, captionLineAt } =
  await import(pathToFileURL(path.join(ROOT, "web/src/composables/captionPresets.js")).href);

const presets = (wanted.length ? wanted : CAPTION_ANIMATIONS.map((p) => p.key))
  .filter((k) => k !== "plain");

// ── the component's own CSS, minus Vue's scoping ──────────────────────────
const sfc = fs.readFileSync(path.join(ROOT, "web/src/components/CaptionPreview.vue"), "utf8");
const css = sfc.slice(sfc.indexOf("<style"), sfc.lastIndexOf("</style>")).replace(/^<style[^>]*>/, "");

function previewMarkup(preset, seconds) {
  const line = captionLineAt(WORDS, seconds, effectiveChunk(preset, SETTINGS.highlight_mode));
  if (!line) return "";

  const typewriter = preset.key === "stream" || preset.key === "news";
  const panelOn = backdrop || preset.panel;
  const cls = [
    "cp", `cp-${preset.key}`,
    line.length > 1 ? "cp-multi" : "",
    panelOn && !preset.panel ? "cp-backdrop" : "",
    !panelOn && preset.panel ? "cp-nopanel" : "",
  ].filter(Boolean).join(" ");

  const words = line.map((w, i) => {
    // Freeze the CSS animation and seek it to this word's elapsed time, so the
    // screenshot shows the same instant the export's \t() does.
    const sourceWord = WORDS.find((candidate) => candidate.text === w.text);
    const elapsed = sourceWord ? Math.max(0, seconds - sourceWord.start) : 0;
    const seek = w.state === "active"
      ? ` style="animation-delay:-${elapsed.toFixed(3)}s"`
      : "";
    let inner;
    if (typewriter) {
      const chars = Array.from(w.text);
      const shown = w.state === "spoken" ? chars.length : Math.round((w.frac ?? 0) * chars.length);
      const lead = i > 0 ? `<span class="cp-ch cp-on">&nbsp;</span>` : "";
      inner = lead + chars
        .map((c, ci) => `<span class="cp-ch${ci < shown ? " cp-on" : ""}">${c}</span>`)
        .join("");
    } else {
      inner = w.text;
    }
    return `<span class="cp-w cp-${w.state}"${seek}>${inner}</span>`;
  }).join("");

  const caret = typewriter ? '<span class="cp-caret"></span>' : "";
  const style = [
    `--cp-hl:${SETTINGS.highlight_style === "plain" ? SETTINGS.color : SETTINGS.highlight_color}`,
    preset.key === "news" && panelOn ? "" : `color:${SETTINGS.color}`,
    SETTINGS.panel_color ? `--cp-bg:${SETTINGS.panel_color}` : "",
    `font-family:'${preset.font || 'Bebas Neue'}',sans-serif`,
  ].filter(Boolean).join(";");

  return `<div class="${cls}" style="${style}">${words}${caret}</div>`;
}

function previewSheet(preset) {
  const frames = TIMES.map((t) => `
    <div class="frame">
      <div class="cap-layer" style="font-size:${EXPORT_FONT}px">${previewMarkup(preset, t)}</div>
    </div>`).join("");

  return `<!doctype html><html><head><meta charset="utf-8">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Montserrat:ital,wght@0,400;0,700;0,800;0,900;1,800;1,900&family=Nunito:wght@400;800&family=Roboto+Mono:wght@400;500&family=Luckiest+Guy&family=Fredoka+One&family=Passion+One:wght@400;700&family=Days+One&family=Orbitron:wght@400;700&family=Permanent+Marker&display=swap">
<style>
  * { box-sizing: border-box; }
  body { margin:0; background:#8a7f6f; display:flex; }
  .frame { width:${W}px; height:${H}px; position:relative; flex:0 0 auto; border-right:4px solid #222; }
  .cap-layer { position:absolute; left:6%; right:6%; bottom:20%; display:flex; justify-content:center; text-align:center; }
  /* Deterministic frames: no transitions, and animations are paused at the
     offset set per word via animation-delay. */
  * { transition: none !important; }
  .cp *, .cp { animation-play-state: paused !important; animation-fill-mode: both !important; }
${css}
</style></head><body>${frames}</body></html>`;
}

function run(cmd, args) {
  return execFileSync(cmd, args, { stdio: ["ignore", "pipe", "pipe"] });
}

function renderPreview(preset) {
  const html = path.join(TMP, `${preset.key}.html`);
  const png = path.join(TMP, `${preset.key}-preview.png`);
  fs.writeFileSync(html, previewSheet(preset));
  run(CHROME, [
    "--headless=new", "--disable-gpu", "--hide-scrollbars",
    `--window-size=${W * TIMES.length + 4 * TIMES.length},${H}`,
    "--virtual-time-budget=8000",
    `--screenshot=${png}`,
    pathToFileURL(html).href,
  ]);
  return png;
}

function renderExport(preset) {
  // The generator is PHP; drive it through the same harness the audit uses.
  const gen = path.join(TMP, "gen.php");
  fs.writeFileSync(gen, phpHarness(preset));
  const ass = path.join(TMP, `${preset.key}.ass`);
  run("php", [gen, ass]);

  const frames = TIMES.map((t, i) => {
    const out = path.join(TMP, `${preset.key}-exp-${i}.png`);
    run("ffmpeg", [
      "-y", "-loglevel", "error",
      "-f", "lavfi", "-i", `color=c=0x8a7f6f:size=${W}x${H}:duration=4:rate=50`,
      "-vf", `subtitles=${ass}`, "-ss", String(t), "-frames:v", "1", "-update", "1", out,
    ]);
    return out;
  });

  const strip = path.join(TMP, `${preset.key}-export.png`);
  run("magick", [...frames, "+append", strip]);
  return strip;
}

function phpHarness(preset) {
  const words = JSON.stringify(WORDS);
  const settings = JSON.stringify({ ...SETTINGS, backdrop: backdrop ? true : null, font: preset.font });
  return `<?php
namespace Illuminate\\Support\\Facades { class Log { public static function warning($m,$c=[]){} } }
namespace Symfony\\Component\\Process {
  class Process { private $cmd; private $out='';
    public function __construct(array $c){ $this->cmd=$c; }
    public function setTimeout($t){}
    public function run(){
      $fam=end($this->cmd); $dir='${ROOT}/api/resources/fonts/'; $file='';
      $want=strtolower(str_replace(' ','',$fam));
      foreach (glob($dir.'*.ttf') as $p) {
        $n=strtolower(str_replace(['-','Regular',' '],['','',''],basename($p,'.ttf')));
        if ($n===$want) { $file=$p; break; }
      }
      $this->out = ($this->cmd[2]==='%{file}') ? $file : ($file!=='' ? $fam : '');
    }
    public function isSuccessful(){ return $this->out!==''; }
    public function getOutput(){ return $this->out; } } }
namespace {
require '${ROOT}/api/app/Services/Media/FontMetrics.php';
function app($cls){ static $i=[]; return $i[$cls] ??= new $cls(); }
require '${ROOT}/api/app/Traits/BuildsAnimatedCaptions.php';
$h = new class { use \\App\\Traits\\BuildsAnimatedCaptions;
  protected function escapeASSText(string $t): string { return str_replace(["{","}","\\n","\\r"],["\\\\{","\\\\}","\\\\N",""],$t); }
  protected function formatASSTime(float $s): string { $cs=(int)round($s*100);$hh=intdiv($cs,360000);$cs%=360000;$m=intdiv($cs,6000);$cs%=6000;$sec=intdiv($cs,100);$cs%=100;return sprintf("%d:%02d:%02d.%02d",$hh,$m,$sec,$cs); }
  public function go($anim,$words,$cs) {
    return $this->buildAnimatedASSContent($anim,$words,[
      "playResX"=>${W},"playResY"=>${H},"alignment"=>2,"marginV"=>400,"marginLR"=>60,
      "fontName"=>$cs['font'] ?: 'Bebas Neue',"fontSize"=>${EXPORT_FONT},
      "primary"=>$cs['color'],"highlight"=>$cs['highlight_color'],
      "highlightStyle"=>$cs['highlight_style'],"panelColor"=>$cs['panel_color'],
      "backdrop"=>$cs['backdrop'],"duration"=>4.0,"highlightMode"=>$cs['highlight_mode'],
    ]);
  }
};
file_put_contents($argv[1], $h->go(${JSON.stringify(preset.key)}, json_decode('${words}', true), json_decode('${settings}', true)));
}
`;
}

fs.mkdirSync(OUT, { recursive: true });
if (!CHROME) {
  console.error("No Chrome/Chromium found — install one or set the path in this script.");
  process.exit(1);
}

for (const key of presets) {
  const preset = animationByKey(key);
  process.stdout.write(`${key.padEnd(10)} `);
  try {
    const exportStrip = renderExport(preset);
    const previewStrip = renderPreview(preset);
    const out = path.join(OUT, `${key}.png`);

    // Stack export over preview, scaled to a readable width, with labels.
    run("magick", [
      "(", exportStrip, "-resize", "1800x", "-bordercolor", "#111", "-border", "0x6",
      "-background", "#111", "-fill", "#7cff9e", "-pointsize", "34",
      "label:EXPORT  (libass)", "+swap", "-gravity", "West", "-append", ")",
      "(", previewStrip, "-resize", "1800x", "-bordercolor", "#111", "-border", "0x6",
      "-background", "#111", "-fill", "#9ecbff", "-pointsize", "34",
      "label:EDITOR PREVIEW  (Chrome)", "+swap", "-gravity", "West", "-append", ")",
      "-append", out,
    ]);
    console.log(`-> ${path.relative(process.cwd(), out)}`);
    if (openWhenDone) run("open", [out]);
  } catch (e) {
    console.log(`FAILED: ${String(e.stderr || e.message).slice(0, 300)}`);
  }
}

console.log(`\nSheets in ${path.relative(process.cwd(), OUT)}  (times: ${TIMES.join("s, ")}s)`);
