<?php
namespace App\Services\Create;

use App\Models\Asset;
use App\Services\Media\StorageService;
use Illuminate\Support\Facades\DB;

/** Approval belongs to these generated bytes and this plan, never just a character name. */
class CharacterApproval
{
    public const CONTRACT = 'approved-master-v2';

    public static function mediaHash(array $item, array $context): string
    {
        $contract = match ($item['kind']) {
            'character_poses' => self::CONTRACT,
            'animate_image' => ($item['subject'] ?? '') === 'approved_character' ? self::CONTRACT.'|motion|'.($item['master_sha256'] ?? '') : '',
            'character_variants' => self::CONTRACT.'|'.($item['master_sha256'] ?? ''),
            default => '',
        };
        return hash('sha256', $contract.$item['kind'].'|'.$item['description'].(! empty($item['requirements']) ? '|requirements:'.json_encode($item['requirements']) : '').'|'.json_encode([
            $context['talking_route'] ?? null, $context['narration'], $context['voice'], $context['aspect_ratio'], $context['character_style'],
        ]));
    }

    public static function candidate(array $plan, array $settings, int $workspace): ?array
    {
        $pose = collect($plan['media'] ?? [])->firstWhere('kind', 'character_poses');
        if (! $pose || empty($plan['plan_id'])) return null;
        $hash = self::mediaHash($pose, ['narration' => $plan['narration'] ?? [], 'voice' => $plan['voice'] ?? null,
            'aspect_ratio' => $settings['aspect_ratio'] ?? '9:16', 'character_style' => $plan['character_style'] ?? '']);
        $row = DB::table('create_plan_media')->where('plan_id', $plan['plan_id'])->where('kind', 'character_poses')
            ->where('description_hash', $hash)->where('status', 'succeeded')->first();
        if (! $row) return null;
        $record = json_decode($row->record_json, true);
        if (($record['character_contract'] ?? null) !== self::CONTRACT) return null;
        $files = array_values(array_filter([$record['file'] ?? null, ...($record['more_files'] ?? [])]));
        if (! $files) return null;
        $images = [];
        foreach ($files as $f) {
            $a = Asset::where('workspace_id', $workspace)->where('status', '!=', 'archived')->find($f['asset_id']);
            if (! $a || $a->asset_type !== 'image') return null;
            $images[] = ['asset_id' => (int) $a->id, 'name' => $a->title, 'preview_url' => app(StorageService::class)->url($a->storage_url)];
        }
        $token = hash('sha256', json_encode([$plan['plan_id'], $hash, array_map(fn ($f) => [$f['asset_id'], $f['sha256']], $files)]));
        return ['token' => $token, 'images' => $images, 'media_id' => $row->id, 'files' => $files];
    }

    public static function requireApproved(array $plan, array $settings, int $workspace): array
    {
        $candidate = self::candidate($plan, $settings, $workspace);
        abort_unless($candidate && hash_equals($candidate['token'], (string) ($plan['character_approval'] ?? '')), 422,
            'Review and approve the character preview before generating poses or the full video. Create a storyboard first if there is no current preview.');
        app(InputSnapshotService::class)->verify($candidate['files']);
        return $candidate;
    }
}
