import assert from 'node:assert/strict';
import {mkdir,copyFile,readFile,writeFile,access} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {renderRun} from './lib/render-run.mjs';
const root='/tmp/reliability';
await mkdir(root,{recursive:true}); await mkdir(process.env.HOME,{recursive:true});
for(const file of ['index.html','product.svg']) await copyFile('/opt/worker/fixtures/'+file,root+'/'+file);
await copyFile('/opt/worker/node_modules/gsap/dist/gsap.min.js',root+'/gsap.min.js');
await copyFile('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',root+'/font.ttf');
const options={project:root,outputRoot:'/output/reliability',expected:{width:1080,height:1920,duration:15}};
const results=[];
const cancelled = new AbortController();
let timer;
results.push(await renderRun({...options,signal:cancelled.signal,onStage:stage=>{if(stage==='render') timer=setTimeout(()=>cancelled.abort(),2000);}})); clearTimeout(timer);
assert.equal(results.at(-1).status,'cancelled');
results.push(await renderRun({...options,timeoutMs:100}));
assert.equal(results.at(-1).status,'failed');
results.push(await renderRun(options)); assert.equal(results.at(-1).status,'ready');
const ready=results.at(-1); const hash=async()=>createHash('sha256').update(await readFile(ready.directory+'/video.mp4')).digest('hex');
const before=await hash();
const html=await readFile(root+'/index.html','utf8');
await writeFile(root+'/index.html',html.replace('./product.svg','./missing-product.svg'));
results.push(await renderRun(options)); assert.equal(results.at(-1).status,'failed');
assert.equal(await hash(),before);
for(const result of results.filter(r=>r.status!=='ready')) await assert.rejects(access(result.directory+'/video.mp4'));
await writeFile('/output/reliability/report.json',JSON.stringify({results,previousArtifactUnchanged:true},null,2));
console.log(JSON.stringify(results,null,2));
