<?php

namespace App\Http\Controllers\Api\V1\Asset;

use App\Http\Controllers\Controller;
use App\Services\Generation\Image\ImageStyleDescriptors;
use App\Services\Media\StorageService;
use Illuminate\Http\JsonResponse;

/**
 * Public catalog of image styles. Used by the onboarding wizard, the New
 * Video modal, and any other surface that wants the canonical list.
 *
 * Reads from ImageStyleDescriptors::META (single source of truth) and
 * decorates each style with its B2 sample_url so consumers can render
 * thumbnails (generated by `php artisan generate:style-samples`).
 */
class ImageStyleController extends Controller
{
    public function index(StorageService $storage): JsonResponse
    {
        $styles = [];
        foreach (ImageStyleDescriptors::META as $key => $meta) {
            $styles[] = [
                'key'         => $key,
                'label'       => $meta['label'],
                'description' => $meta['description'],
                'sample_url'  => $storage->url("style-samples/{$key}.jpg"),
            ];
        }
        return response()->json([
            'data' => $styles,
            'meta' => ['total' => count($styles)],
        ]);
    }
}
