<?php

namespace Database\Seeders;

use App\Models\Template;
use Illuminate\Database\Seeder;

class TemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'name' => 'Explainer',
                'template_type' => 'explainer',
                'description' => 'Hook-first educational short with paced narration and clear CTA close.',
                'scene_structure_json' => [
                    ['type' => 'hook', 'duration_seconds' => 4],
                    ['type' => 'narration', 'duration_seconds' => 9],
                    ['type' => 'narration', 'duration_seconds' => 9],
                    ['type' => 'narration', 'duration_seconds' => 8],
                    ['type' => 'text_card', 'duration_seconds' => 3],
                ],
                'caption_style_json' => [
                    'preset_hint' => 'Bold Focus',
                    'highlight_mode' => 'word_by_word',
                ],
                'voice_style_json' => [
                    'pace' => 'medium',
                    'energy' => 'confident',
                ],
                'color_font_rules_json' => [
                    'font_primary' => 'Poppins',
                    'contrast' => 'high',
                ],
                'transition_rules_json' => [
                    'default' => 'cut',
                    'scene_boundary' => 'quick_swipe',
                ],
                'timing_rules_json' => [
                    'target_total_seconds' => 33,
                    'max_total_seconds' => 45,
                ],
                'supported_formats' => ['9:16', '1:1', '16:9'],
                'supported_languages' => ['en'],
                'status' => 'active',
            ],
            [
                'name' => 'Listicle',
                'template_type' => 'listicle',
                'description' => 'Numbered format optimized for quick scanning and retention hooks.',
                'scene_structure_json' => [
                    ['type' => 'hook', 'duration_seconds' => 4],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Point 1'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Point 2'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Point 3'],
                    ['type' => 'text_card', 'duration_seconds' => 3],
                ],
                'caption_style_json' => [
                    'preset_hint' => 'Clean Story',
                    'highlight_mode' => 'keywords',
                ],
                'voice_style_json' => [
                    'pace' => 'medium_fast',
                    'energy' => 'dynamic',
                ],
                'color_font_rules_json' => [
                    'font_primary' => 'Manrope',
                    'contrast' => 'high',
                ],
                'transition_rules_json' => [
                    'default' => 'cut',
                    'scene_boundary' => 'flash',
                ],
                'timing_rules_json' => [
                    'target_total_seconds' => 28,
                    'max_total_seconds' => 40,
                ],
                'supported_formats' => ['9:16', '1:1'],
                'supported_languages' => ['en'],
                'status' => 'active',
            ],
            // Niche templates
            [
                'name' => 'Horror Storytime',
                'template_type' => 'listicle',
                'description' => 'Dark atmospheric hook, 5–8 story beats, twist outro. Optimised for horror and paranormal niches.',
                'scene_structure_json' => [
                    ['type' => 'hook', 'duration_seconds' => 5, 'label' => 'Hook'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Setup'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Rising tension'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Escalation'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Climax'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Twist outro'],
                    ['type' => 'text_card', 'duration_seconds' => 3],
                ],
                'caption_style_json' => ['preset_hint' => 'Bold Focus', 'highlight_mode' => 'word_by_word'],
                'voice_style_json' => ['pace' => 'slow_build', 'energy' => 'dramatic'],
                'color_font_rules_json' => ['font_primary' => 'Poppins', 'contrast' => 'high', 'visual_style' => 'dark'],
                'transition_rules_json' => ['default' => 'cut', 'scene_boundary' => 'fade'],
                'timing_rules_json' => ['target_total_seconds' => 47, 'max_total_seconds' => 60],
                'supported_formats' => ['9:16'],
                'supported_languages' => ['en'],
                'status' => 'active',
            ],
            [
                'name' => 'Finance Tips',
                'template_type' => 'explainer',
                'description' => 'Credibility hook, 3–5 actionable tip scenes, strong CTA. Optimised for finance and money niches.',
                'scene_structure_json' => [
                    ['type' => 'hook', 'duration_seconds' => 4, 'label' => 'Hook'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Tip 1'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Tip 2'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Tip 3'],
                    ['type' => 'narration', 'duration_seconds' => 6, 'label' => 'CTA'],
                    ['type' => 'text_card', 'duration_seconds' => 3],
                ],
                'caption_style_json' => ['preset_hint' => 'Clean Story', 'highlight_mode' => 'keywords'],
                'voice_style_json' => ['pace' => 'medium', 'energy' => 'authoritative'],
                'color_font_rules_json' => ['font_primary' => 'Manrope', 'contrast' => 'high', 'visual_style' => 'documentary'],
                'transition_rules_json' => ['default' => 'cut', 'scene_boundary' => 'quick_swipe'],
                'timing_rules_json' => ['target_total_seconds' => 37, 'max_total_seconds' => 50],
                'supported_formats' => ['9:16', '1:1'],
                'supported_languages' => ['en'],
                'status' => 'active',
            ],
            [
                'name' => 'Motivation',
                'template_type' => 'explainer',
                'description' => 'Quote hook, 4–6 insight scenes, challenge CTA. Warm cinematic visuals.',
                'scene_structure_json' => [
                    ['type' => 'hook', 'duration_seconds' => 4, 'label' => 'Quote hook'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Insight 1'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Insight 2'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Insight 3'],
                    ['type' => 'narration', 'duration_seconds' => 6, 'label' => 'Challenge CTA'],
                    ['type' => 'text_card', 'duration_seconds' => 3],
                ],
                'caption_style_json' => ['preset_hint' => 'Bold Focus', 'highlight_mode' => 'word_by_word'],
                'voice_style_json' => ['pace' => 'medium_fast', 'energy' => 'energetic'],
                'color_font_rules_json' => ['font_primary' => 'Poppins', 'contrast' => 'high', 'visual_style' => 'cinematic'],
                'transition_rules_json' => ['default' => 'cut', 'scene_boundary' => 'quick_swipe'],
                'timing_rules_json' => ['target_total_seconds' => 34, 'max_total_seconds' => 45],
                'supported_formats' => ['9:16'],
                'supported_languages' => ['en'],
                'status' => 'active',
            ],
            [
                'name' => 'Dark History',
                'template_type' => 'listicle',
                'description' => 'Hook + 4–7 historical fact scenes + conclusion. Documentary visual style.',
                'scene_structure_json' => [
                    ['type' => 'hook', 'duration_seconds' => 4, 'label' => 'Hook'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Fact 1'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Fact 2'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Fact 3'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Fact 4'],
                    ['type' => 'narration', 'duration_seconds' => 6, 'label' => 'Conclusion'],
                    ['type' => 'text_card', 'duration_seconds' => 3],
                ],
                'caption_style_json' => ['preset_hint' => 'Clean Story', 'highlight_mode' => 'keywords'],
                'voice_style_json' => ['pace' => 'medium', 'energy' => 'neutral'],
                'color_font_rules_json' => ['font_primary' => 'Manrope', 'contrast' => 'high', 'visual_style' => 'documentary'],
                'transition_rules_json' => ['default' => 'cut', 'scene_boundary' => 'fade'],
                'timing_rules_json' => ['target_total_seconds' => 45, 'max_total_seconds' => 58],
                'supported_formats' => ['9:16', '1:1'],
                'supported_languages' => ['en'],
                'status' => 'active',
            ],
            [
                'name' => 'Science Breakdown',
                'template_type' => 'explainer',
                'description' => 'Hook + 5 explanation scenes + summary. Clean minimalist visuals.',
                'scene_structure_json' => [
                    ['type' => 'hook', 'duration_seconds' => 4, 'label' => 'Hook'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Concept intro'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'How it works'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Why it matters'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Real-world example'],
                    ['type' => 'narration', 'duration_seconds' => 5, 'label' => 'Summary'],
                    ['type' => 'text_card', 'duration_seconds' => 3],
                ],
                'caption_style_json' => ['preset_hint' => 'Clean Story', 'highlight_mode' => 'keywords'],
                'voice_style_json' => ['pace' => 'medium', 'energy' => 'clear'],
                'color_font_rules_json' => ['font_primary' => 'Manrope', 'contrast' => 'high', 'visual_style' => 'minimalist'],
                'transition_rules_json' => ['default' => 'cut', 'scene_boundary' => 'quick_swipe'],
                'timing_rules_json' => ['target_total_seconds' => 43, 'max_total_seconds' => 55],
                'supported_formats' => ['9:16', '1:1'],
                'supported_languages' => ['en'],
                'status' => 'active',
            ],
            [
                'name' => 'True Crime',
                'template_type' => 'listicle',
                'description' => 'Intro + case scenes + resolution. Cinematic dark atmosphere.',
                'scene_structure_json' => [
                    ['type' => 'hook', 'duration_seconds' => 5, 'label' => 'Case intro'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Background'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'The incident'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'Investigation'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Resolution'],
                    ['type' => 'text_card', 'duration_seconds' => 3],
                ],
                'caption_style_json' => ['preset_hint' => 'Bold Focus', 'highlight_mode' => 'word_by_word'],
                'voice_style_json' => ['pace' => 'slow_build', 'energy' => 'dramatic'],
                'color_font_rules_json' => ['font_primary' => 'Poppins', 'contrast' => 'high', 'visual_style' => 'dark'],
                'transition_rules_json' => ['default' => 'cut', 'scene_boundary' => 'fade'],
                'timing_rules_json' => ['target_total_seconds' => 39, 'max_total_seconds' => 52],
                'supported_formats' => ['9:16'],
                'supported_languages' => ['en'],
                'status' => 'active',
            ],
            [
                'name' => 'Product Walkthrough',
                'template_type' => 'explainer',
                'description' => 'Hook + feature scenes + CTA. Realistic clean visuals for product review content.',
                'scene_structure_json' => [
                    ['type' => 'hook', 'duration_seconds' => 4, 'label' => 'Hook'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Overview'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Feature 1'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'Feature 2'],
                    ['type' => 'narration', 'duration_seconds' => 6, 'label' => 'Verdict & CTA'],
                    ['type' => 'text_card', 'duration_seconds' => 3],
                ],
                'caption_style_json' => ['preset_hint' => 'Clean Story', 'highlight_mode' => 'keywords'],
                'voice_style_json' => ['pace' => 'medium', 'energy' => 'friendly'],
                'color_font_rules_json' => ['font_primary' => 'Manrope', 'contrast' => 'high', 'visual_style' => 'realistic'],
                'transition_rules_json' => ['default' => 'cut', 'scene_boundary' => 'quick_swipe'],
                'timing_rules_json' => ['target_total_seconds' => 34, 'max_total_seconds' => 45],
                'supported_formats' => ['9:16', '1:1', '16:9'],
                'supported_languages' => ['en'],
                'status' => 'active',
            ],
            [
                'name' => 'Self Improvement',
                'template_type' => 'explainer',
                'description' => 'Hook + habit scenes + challenge CTA. Warm minimal aesthetic for personal growth content.',
                'scene_structure_json' => [
                    ['type' => 'hook', 'duration_seconds' => 4, 'label' => 'Hook'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'The problem'],
                    ['type' => 'narration', 'duration_seconds' => 8, 'label' => 'The habit'],
                    ['type' => 'narration', 'duration_seconds' => 7, 'label' => 'How to start'],
                    ['type' => 'narration', 'duration_seconds' => 6, 'label' => '30-day challenge'],
                    ['type' => 'text_card', 'duration_seconds' => 3],
                ],
                'caption_style_json' => ['preset_hint' => 'Clean Story', 'highlight_mode' => 'keywords'],
                'voice_style_json' => ['pace' => 'medium', 'energy' => 'calm'],
                'color_font_rules_json' => ['font_primary' => 'Manrope', 'contrast' => 'high', 'visual_style' => 'minimalist'],
                'transition_rules_json' => ['default' => 'cut', 'scene_boundary' => 'quick_swipe'],
                'timing_rules_json' => ['target_total_seconds' => 35, 'max_total_seconds' => 47],
                'supported_formats' => ['9:16'],
                'supported_languages' => ['en'],
                'status' => 'active',
            ],
        ];

        foreach ($templates as $template) {
            Template::query()->updateOrCreate(
                [
                    'workspace_id' => null,
                    'name' => $template['name'],
                ],
                $template,
            );
        }
    }
}
